name: Continuous Integration
on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET v8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
    - name: Build .NET files
      run: dotnet build
    - name: Test .NET
      run: dotnet test
    - name: Install npm dependencies
      working-directory: DotnetTemplate.Web
      run: npm i
    - name: Lint
      working-directory: DotnetTemplate.Web
      run: npm run lint
    - name: Test node files
      working-directory: DotnetTemplate.Web
      run: npm t