name: Continuous Integration test
on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET v8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
    - name: Build .NET files
      run: dotnet build
    - name: Test .NET
      run: dotnet test
    - name: Install npm packages
      run: cd ./DotnetTemplate.Web && npm i
    - name: Lint
      run: cd ./DotnetTemplate.Web && npm run lint
    - name: Test node files
      run: cd ./DotnetTemplate.Web && npm t